# Generated by Django 5.0.6 on 2024-08-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_car_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='violation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
