# Generated by Django 5.0.6 on 2024-08-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_car_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='violation',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
