# Generated by Django 5.0.6 on 2024-08-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_car_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, verbose_name='車牌')),
                ('date_time', models.DateTimeField(verbose_name='日期時間')),
                ('location', models.CharField(max_length=255, verbose_name='地點')),
                ('violation', models.CharField(max_length=50, verbose_name='違規種類')),
                ('image_url', models.URLField(verbose_name='違規影片')),
            ],
            options={
                'verbose_name': '車輛',
                'verbose_name_plural': '車辆',
            },
        ),
    ]
