# Generated by Django 5.0.6 on 2024-08-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('violation', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
