# Generated by Django 5.0.6 on 2024-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_video_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/', verbose_name='車輛圖片'),
        ),
    ]
